language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

os:
    - linux

compiler:
    - gcc
    - clang

services: docker
sudo: required

addons:
    apt:
        packages:
            - cmake
            - cmake-data

matrix:
    fast_finish: true
    include:
        - os: linux
          compiler: clang
          env: SCAN="scan-build --status-bugs"
        - env: WERROR="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Werror"
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=2.7
          python: 2.7
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.4
          python: 3.4
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.5
          python: 3.5
        - os: osx
          language: generic
          env: MB_PYTHON_VERSION=3.6
          python: 3.6

before_install:
    - unset -f pushd
    - unset -f popd
    - git clone https://github.com/matthew-brett/multibuild
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - pip install bandit setuptools pytest pytest-runner pybind11
    - bandit -c bandit.yml -r python/

before_script:
    - mkdir build
    - pushd build
    - $SCAN cmake -DCMAKE_BUILD_TYPE=Release
                  -DBUILD_SHARED_LIBS=ON
                  ${WERROR}
                  ..
    - popd

script:
    - pushd build
    - make
    - ctest --output-on-failure
